export interface Sport {
  id: string;
  name: string;
  teams: string[];
}

export const SPORTS_DATA: Sport[] = [
  {
    id: "chess",
    name: "Chess",
    teams: [
      "UG2023 BongCloud",
      "UG2023 Pawn stars",
      "UG2024 Bobby Fisther",
      "Tal's Terrorists",
      "UG25 rookies",
      "PhD The Royal Fork",
      "YIF2025 UNFORTUNATELY",
    ],
  },
  {
    id: "football",
    name: "Football",
    teams: [
      "UG2024 SonipatStrikers",
      "Jet2Holiday",
      "UG2023 Adhoka United",
      "UG2026 Mallikagang",
    ],
  },
  {
    id: "frisbee",
    name: "Frisbee",
    teams: [
      "UG2023 PowerOfFriendship",
      "Aiyoo Ok",
      "Grazing Goats",
      "Disc-o-Deewane",
      "UG2023 Rizz Bees",
      "UG2025 Huck Yeah!",
      "UG2025 EmeraldEdgers",
    ],
  },
  {
    id: "pool",
    name: "Pool",
    teams: [
      "whatv",
      "UG2023 Cue-ties",
      "UG2023 SolidBalls",
      "The Jaideepers",
      "UG2023 Sticks & Stones",
      "ballbangers",
      "UG2023 Cue-Cumber",
      "UG2023 HOTSHOTS",
      "UG2023 DOUBLEBREAKERS",
    ],
  },
  {
    id: "beachvolleyball",
    name: "Beach Volleyball",
    teams: [
      "UG25 ThreeFourthsDosa",
      "UG2025 First Year Frogs (5)",
      "UG2024 Bad Beaches (7)",
      "The Jaideepers",
      "UG2023 FriendshipOfPower (6)",
      "afghan proverb",
      "Sets on the Beach (4)",
      "Ug2024 TeamName (3)",
      "Pizza Ice Cream (2)",
      "ug2023 ball (1)",
      "Four Shore",
    ],
  },
  {
    id: "table-tennis",
    name: "Table Tennis",
    teams: [
      "Mihika Mehta",
      "Radhika Tandon",
      "Pearl Naik",
      "Tejal Kaur",
      "Ojal Rao",
      "Amirtha Apollo",
      "Reva Agarwal",
      "Hrithika Tom",
      "Aditi Parmar",
      "Darshana Baishya",
      "Samridhya",
      "Aishani Saurabh",
      "Avisikta Sinha",
      "Aarya",
    ],
  },
  {
    id: "swimming",
    name: "Swimming",
    teams: [
      "Raj Choudhary",
      "Chaitanya Gupta",
      "Shreyas Jhajharia",
      "Rohan Marballi",
      "Aryan Nath",
      "Dharmendra Mahto",
      "Advay Almal",
      "Shashank Singh",
    ],
  },
  {
    id: "shooting",
    name: "Shooting",
    teams: [
      "Ananya Agarwal",
      "Manas Karthik",
      "Lakshita Panghal",
      "Alaaya Bahl",
      "Preksha",
      "Arushi Malhotra",
      "Varun Muchhal",
      "Advay Awasthy",
      "Abhinav Hari",
      "Trigya Dhir",
      "Hiral Thakur",
      "Siya Kohli",
      "Shreya Singhal",
    ],
  },
];
